Instagram/Models/Picture.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Picture()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Pname { get; set; }
        public string like { get; set; }
        public string User_id { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}

Instagram/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Instagram;

namespace Instagram.Controllers
{
    public class CommentsController : Controller
    {
        private InstagramContainer db = new InstagramContainer();

        // GET: Comments
        public ActionResult Index()
        {
            var commentSet = db.CommentSet.Include(c => c.User).Include(c => c.Picture);
            return View(commentSet.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.CommentSet.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username");
            ViewBag.PictureId = new SelectList(db.PictureSet, "Id", "Path");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Comment_Text,Date_Time,UserId,PictureId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.CommentSet.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username", comment.UserId);
            ViewBag.PictureId = new SelectList(db.PictureSet, "Id", "Path", comment.PictureId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.CommentSet.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username", comment.UserId);
            ViewBag.PictureId = new SelectList(db.PictureSet, "Id", "Path", comment.PictureId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Comment_Text,Date_Time,UserId,PictureId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username", comment.UserId);
            ViewBag.PictureId = new SelectList(db.PictureSet, "Id", "Path", comment.PictureId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.CommentSet.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.CommentSet.Find(id);
            db.CommentSet.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Instagram/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Instagram;
using System.IO;

namespace Instagram.Controllers
{
    public class PicturesController : Controller
    {
        private InstagramContainer db = new InstagramContainer();

        // GET: Pictures
        public ActionResult Index()
        {
            var pictureSet = db.PictureSet.Include(p => p.User);
            return View(pictureSet.ToList());
        }

        // GET: Pictures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.PictureSet.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // GET: Pictures/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username");
            return View();
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Path,Caption,Like,UserId")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.PictureSet.Add(picture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username", picture.UserId);
            return View(picture);
        }

        public ActionResult FileUpload(HttpPostedFileBase file, string caption)
        {
            if (file != null)
            {
                string pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(
                                       Server.MapPath("../images"), pic);
                // file is uploaded
                file.SaveAs(path);

                path = "../images/" + pic;
                Picture picture = new Picture();
                picture.Caption = caption;
                picture.Path = path;
                picture.Like = 0.ToString();
                picture.UserId = Convert.ToInt32(Session["userID"]);

                db.PictureSet.Add(picture);
                db.SaveChanges();

                // save the image path path to the database or you can send image
                // directly to database
                // in-case if you want to store byte[] ie. for DB
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }

            }
            // after successfully uploading redirect the user
            return RedirectToAction("Index", "Pictures");
        }

        // GET: Pictures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.PictureSet.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username", picture.UserId);
            return View(picture);
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Path,Caption,Like,UserId")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(picture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserSet, "Id", "Username", picture.UserId);
            return View(picture);
        }

        // GET: Pictures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.PictureSet.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Pictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.PictureSet.Find(id);
            db.PictureSet.Remove(picture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Instagram/Views/Pictures/Create.cshtml
@model Instagram.Picture

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("FileUpload", "Pictures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="file">Upload Image:</label>
            <input type="file" name="file" id="file" style="width: 100%;" />
            <textarea name="caption" id="caption"></textarea>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Instagram/Views/Pictures/Delete.cshtml
@model Instagram.Picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Like)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Like)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Instagram/Views/Pictures/Details.cshtml
@model Instagram.Picture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Like)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Like)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Instagram/Views/Pictures/Edit.cshtml
@model Instagram.Picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Caption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Like, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Like, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Like, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Instagram/Views/Pictures/Index.cshtml
@model IEnumerable<Instagram.Picture>

@{
    ViewBag.Title = "Index";
}
<br />
@foreach (var item in Model)
{
    <div class="row">
        <div class="pic-frame">
            <p>@Html.DisplayFor(modelItem => item.User.Username)</p>
            <img src="@Html.DisplayFor(modelItem => item.Path)" class="img-responsive pic" />
            <span class="glyphicon glyphicon-heart"></span>@Html.DisplayFor(modelItem => item.Like) Like
            <p><strong>@Html.DisplayFor(modelItem => item.User.Username)</strong> @Html.DisplayFor(modelItem => item.Caption)</p>

            @if (Session["userName"] != null)
                {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>@Html.ActionLink("Comment", "Create", "Comments")</li>
                        <li>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</li>

                    </ul>
                </div>

            }

        </div>
    </div>
    <br />
}
<style>
    .pic-frame {
        margin: 0 auto;
        max-width: 500px;
        max-height: 500px;
        border: 1px solid #f2f2f2;
    }

    .pic {
        margin: 0 auto;
        padding: 10px 5px;
        max-height: 400px;
    }
</style>